server:
  port: 8762
spring:
  application:
    name: admin-server
eureka:
  instance:
    #表示eureka client发送心跳给server端的频率，默认为30秒
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
  client:
    #表示eureka client间隔多久去拉取服务注册信息，默认为30秒
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

# slf4j日志配置
logging:
  # 配置级别
  level:
    #分包配置级别，即不同的目录下可以使用不同的级别，日志级别总共有
    #TARCE < DEBUG < INFO < WARN < ERROR < FATAL ，且级别是逐渐提供，如果日志级别设置为INFO，则意味级别低的TRACE和DEBUG级别的日志都看不到。
    root: info
  # 指定输出日志的文件名，默认输出至当前项目目录下
  file: /Users/royhsu/workspace/logs/blog-logs/admin-server.log
  pattern:
    console: "%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n"
    file: "%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n"
