eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: blog-zuul
zuul:
  routes:
    artical:
      path: /artical/**
      serviceId: artical-server
    admin:
      path: /admin/**
      serviceId: admin-server
