eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: zuul
    prefer-ip-address: true
server:
  port: 8769

zuul:
  routes:
    article:
      path: /article/**
      serviceId: article-server
    admin:
      path: /admin/**
      serviceId: admin-server
  ignored-services: article-server,admin-server
# slf4j日志配置
logging:
  # 配置级别
  level:
    #分包配置级别，即不同的目录下可以使用不同的级别，日志级别总共有
    #TARCE < DEBUG < INFO < WARN < ERROR < FATAL ，且级别是逐渐提供，如果日志级别设置为INFO，则意味级别低的TRACE和DEBUG级别的日志都看不到。
    root: info
  # 指定输出日志的文件名，默认输出至当前项目目录下
  file: /Users/royhsu/workspace/logs/blog-logs/blog-zuul.log
  pattern:
    console: "%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n"
    file: "%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n"



spring:
  application:
    name: blog-zuul
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testjdbc?useUnicode=true&characterEncoding=utf8
    username: root
    password: 692806
    #2.1版本后，添加druid-spring-boot-starter依赖，可以直接联想出相关配置，且省略配置类
    druid:
      #初始
      initial-size: 5
      #最小空闲
      min-idle: 5
      #最大活动
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #每隔一分钟检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-Query: SELECT 1 FROM DUAL
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      # 配置DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      # 配置DruidStatViewServlet
      stat-view-servlet:
        url-pattern: "/druid/*"
        # IP白名单(没有配置或者为空，则允许所有访问)
        # allow:
        # IP黑名单 (存在共同时，deny优先于allow)
        # deny: 192.168.1.73
        #  禁用HTML页面上的“Reset All”功能
        reset-enable: false
        # 登录名
        login-username: admin
        # 登录密码
        login-password: 123456
  thymeleaf:
    prefix: classpath:/templates/  #prefix：指定模板所在的目录
    check-template-location: true  #check-template-location: 检查模板路径是否存在
    cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
    suffix:  .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html


  devtools:
    livereload:
      enabled: true #是否支持livereload
      port: 35729
    restart:
      enabled: true #是否支持热部署