#2.1版本后，添加druid-spring-boot-starter依赖，可以直接联想出相关配置，且省略配置类
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testjdbc?useUnicode=true&characterEncoding=utf8
    username: root
    password: 692806
    druid:
      #初始
      initial-size: 5
      #最小空闲
      min-idle: 5
      #最大活动
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #每隔一分钟检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-Query: SELECT 1 FROM DUAL
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      # 配置DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      # 配置DruidStatViewServlet
      stat-view-servlet:
        url-pattern: "/druid/*"
        # IP白名单(没有配置或者为空，则允许所有访问)
        # allow:
        # IP黑名单 (存在共同时，deny优先于allow)
        # deny: 192.168.1.73
        #  禁用HTML页面上的“Reset All”功能
        reset-enable: false
        # 登录名
        login-username: admin
        # 登录密码
        login-password: 123456




mybatis-plus:
  mapper-locations: classpath:/mapper/*mapper.xml
  type-aliases-package: com.lyc.mapper
  global-config:
    db-config:
      #主键自增
      id-type: auto
      #字段非空
      field-strategy: not_empty
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false