





mybatis-plus:
  mapper-locations: classpath:/mapper/*mapper.xml
  type-aliases-package: com.lyc.mapper
  global-config:
    db-config:
      #主键自增
      id-type: auto
      #字段非空
      field-strategy: not_empty
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false